// <auto-generated />
using System;
using Idestro.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Idestro.Server.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20230907085340_Initial_2")]
    partial class Initial_2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Idestro.Shared.Models.ConvertFile", b =>
                {
                    b.Property<string>("ProjectDesc")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("JobDesc")
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<string>("FmtNo")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<string>("FileDesc")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime>("UploadDtm")
                        .HasColumnType("datetime2");

                    b.Property<string>("UploadUsr")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("ProjectDesc", "JobDesc", "FmtNo", "FileDesc");

                    b.ToTable("ConvertFiles");
                });

            modelBuilder.Entity("Idestro.Shared.Models.FieldMst", b =>
                {
                    b.Property<string>("ProjectDesc")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("JobDesc")
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<string>("FmtNo")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<string>("FldNo")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<int?>("FldLen")
                        .HasColumnType("int");

                    b.Property<string>("FldUse")
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("IdesFldDesc")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("LastCol")
                        .HasColumnType("int");

                    b.Property<int?>("StartCol")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UploadDtm")
                        .HasColumnType("datetime2");

                    b.Property<string>("UploadUsr")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("ProjectDesc", "JobDesc", "FmtNo", "FldNo");

                    b.ToTable("FieldMst");
                });
#pragma warning restore 612, 618
        }
    }
}
